### PR TITLE
Add osx_arm64 build to v1.2.0

### PR DESCRIPTION
**Pull request by emthompson-usgs**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by emthompson-usgs** [comment]
@ocefpaf I tried installing on a mac with the m1 chip and it didn't work, so this is an attempt to add the macOS ARM build to the recipe.

**Comment by ocefpaf** [comment]
We need to trigger a migration to ensure all the dependencies are available. I put a request in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5472

**Comment by ocefpaf** [comment]
See #4. While all the dependencies were already available we had to:
1. use the numpy in the pinnings, the one in the metadata was too old
2. pin cython in the cross-compilation

**Comment by emthompson-usgs** [comment]
Thanks @ocefpaf!

**Pull request closed without merging**
