### PR TITLE
Version 1.2.0

### PR DESCRIPTION
**Pull request by emthompson-usgs**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by emthompson-usgs** [comment]
@conda-forge-admin, please rerender

**Comment by emthompson-usgs** [comment]
@ocefpaf This is my attempt to update this package. Note: I changed the source url to code.usgs.gov since that is where the source package is (it isn't in pypi for some reason).

**Comment by ocefpaf** [comment]
I tried something here that may work. However, it would be nice to get the sdist on PyPI so we can use its metadata to update the recipe automatically.

**Comment by emthompson-usgs** [comment]
Thanks. I'll work on getting the sdist to pypi. There will be some delay because I'm not the maintainer, but I've contacted the maintainer to add me to the project.

**Comment by ocefpaf** [comment]
@emthompson-usgs does this look OK for you?

**Comment by emthompson-usgs** [comment]
@ocefpaf Yes, thanks so much for taking care of it. I will do a new release when I can fix the sdist issue.

**Pull request merged**
